spring.application.name=voting
## ===============================
## = H2 DATABASE CONFIGURATION  =
## ===============================
#
#spring.datasource.url=jdbc:h2:mem:votingdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
## Enable H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


# ===============================
# = REDIS CONFIGURATION        =
# ===============================
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.redis.password=yourpassword
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


#===================Email config---------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=78kishorem@gmail.com
spring.mail.password=drmqanpmaebsynam
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# (Optional) timeout
#spring.data.redis.timeout=60000


# ===============================
# = CACHE CONFIGURATION        =
# ===============================

#spring.cache.type=redis